"use client"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { PromotionProductPicker, type PromotionProductSelection } from "@/components/promotion-product-picker"
import type { Category, Product } from "@/lib/types"
import { temporaryId, type EditorNode, type EditorOption } from "./types"

interface Props { node: EditorNode; products: Product[]; categories: Category[]; onUpdate: (node: EditorNode) => void; onMarkAsEntry: () => void; onAddEdge: () => void; canDelete: boolean; onDelete: () => void; onClose: () => void }
const number = (value: string, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback

export function StepEditPanel({ node, products, categories, onUpdate, onMarkAsEntry, onAddEdge, canDelete, onDelete, onClose }: Props) {
  const update = (patch: Partial<EditorNode>) => onUpdate({ ...node, ...patch })
  const updateOption = (index: number, patch: Partial<EditorOption>) => update({ options: node.options.map((option, current) => current === index ? { ...option, ...patch } : option) })
  const removeOption = (index: number) => update({ options: node.options.filter((_, current) => current !== index).map((option, current) => ({ ...option, sortOrder: current })) })
  const addOption = () => update({ options: [...node.options, { id: temporaryId("option"), source: "manual", label: "Nueva opción", refProductId: null, refCategoryId: null, refVariantName: null, allowVariantChoice: false, priceMode: "delta", priceDelta: "0", emitsChildItem: false, sortOrder: node.options.length, active: true, priceOverrides: [] }] })
  const selectionFor = (option: EditorOption): PromotionProductSelection => option.source === "category" && option.refCategoryId
    ? { applyTo: "category", categoryId: option.refCategoryId, productIds: [] }
    : { applyTo: "specific_products", categoryId: "", productIds: option.refProductId ? [option.refVariantName ? `${option.refProductId}::${option.refVariantName}` : option.refProductId] : [] }
  const setReference = (index: number, next: PromotionProductSelection) => {
    if (next.applyTo === "category") {
      updateOption(index, { source: "category", refCategoryId: next.categoryId || null, refProductId: null, refVariantName: null })
      return
    }
    // PromotionProductPicker identifies a variant as `productId::variant`.
    // The old code saved that whole value as a product UUID (or discarded the
    // variant) and appeared to retain only the first variant in a flow.
    const selected = next.productIds[0] ?? ""
    const separator = selected.indexOf("::")
    const refProductId = separator === -1 ? selected || null : selected.slice(0, separator) || null
    const refVariantName = separator === -1 ? null : selected.slice(separator + 2) || null
    updateOption(index, { source: "product", refProductId, refCategoryId: null, refVariantName })
  }
  return <aside className="absolute right-0 top-0 z-20 h-full w-[28rem] overflow-y-auto border-l bg-card shadow-xl">
    <div className="space-y-5 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Editar nodo</h2><p className="text-xs text-muted-foreground">{node.options.length === 0 ? "Nodo de paso: el motor lo atraviesa sin mostrarlo." : "Configura la pregunta y sus opciones."}</p></div><Button size="sm" variant="ghost" onClick={onClose}>Cerrar</Button></div>
      <section className="space-y-3 border-b pb-5"><div className="space-y-1"><Label>Título</Label><Input value={node.title} onChange={(event) => update({ title: event.target.value })} /></div><div className="space-y-1"><Label>Subtítulo</Label><Input value={node.subtitle ?? ""} onChange={(event) => update({ subtitle: event.target.value || null })} /></div><div className="grid grid-cols-2 gap-3"><label className="space-y-1 text-sm"><span>Modo</span><select className="w-full rounded-md border bg-background p-2" value={node.selectMode} onChange={(event) => update({ selectMode: event.target.value as "single" | "multi" })}><option value="single">Una opción</option><option value="multi">Varias opciones</option></select></label><label className="space-y-1 text-sm"><span>Mínimo</span><Input type="number" min="0" value={node.minSelections} onChange={(event) => update({ minSelections: number(event.target.value) })} /></label><label className="space-y-1 text-sm"><span>Máximo</span><Input type="number" min="0" placeholder="Sin límite" value={node.maxSelections ?? ""} onChange={(event) => update({ maxSelections: event.target.value === "" ? null : number(event.target.value) })} /></label><label className="flex items-end gap-2 pb-2 text-sm"><Switch checked={node.isEntry} onCheckedChange={onMarkAsEntry} /> Marcar como nodo de entrada</label></div><p className="text-xs text-muted-foreground">Solo puede haber una entrada. Al marcar este nodo, los demás dejan de ser entrada.</p><div className="flex items-center justify-between"><Label>Incluir “ninguno”</Label><Switch checked={node.includeNoneOption} onCheckedChange={(includeNoneOption) => update({ includeNoneOption })} /></div>{node.includeNoneOption && <div className="space-y-1"><Label>Etiqueta de “ninguno”</Label><Input value={node.noneLabel ?? ""} placeholder={`Sin ${node.title || "selección"}`} onChange={(event) => update({ noneLabel: event.target.value || null })} /></div>}</section>
      <section className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Opciones</h3><p className="text-xs text-muted-foreground">Una opción de producto igual reemplaza a la expandida por categoría en este nodo.</p></div><Button size="sm" onClick={addOption}>Agregar</Button></div>
      {node.options.map((option, index) => <div key={option.id} className="space-y-3 rounded-lg border p-3"><div className="flex items-center justify-between"><strong className="text-sm">Opción {index + 1}</strong><Button size="sm" variant="ghost" className="text-destructive" onClick={() => removeOption(index)}>Eliminar</Button></div><label className="space-y-1 text-sm"><span>Fuente</span><select className="w-full rounded-md border bg-background p-2" value={option.source} onChange={(event) => updateOption(index, { source: event.target.value as EditorOption["source"], refProductId: null, refCategoryId: null })}><option value="manual">Texto manual</option><option value="product">Producto real</option><option value="category">Categoría completa</option></select></label>{option.source === "manual" ? <div className="space-y-1"><Label>Texto</Label><Input value={option.label ?? ""} onChange={(event) => updateOption(index, { label: event.target.value })} /></div> : <PromotionProductPicker products={products} categories={categories} value={selectionFor(option)} onChange={(next) => setReference(index, next)} />}
      {option.source === "product" && <><label className="space-y-1 text-sm"><span>Variante concreta (opcional)</span><Input value={option.refVariantName ?? ""} onChange={(event) => updateOption(index, { refVariantName: event.target.value || null })} /></label><label className="flex items-center gap-2 text-sm"><Switch checked={option.allowVariantChoice} onCheckedChange={(allowVariantChoice) => updateOption(index, { allowVariantChoice })} /> Permitir que el mesero elija variante</label></>}
      <div className="grid grid-cols-2 gap-2"><label className="space-y-1 text-sm"><span>Precio</span><select className="w-full rounded-md border bg-background p-2" value={option.priceMode} onChange={(event) => updateOption(index, { priceMode: event.target.value as EditorOption["priceMode"] })}><option value="free">Gratis</option><option value="product_price">Precio de producto</option><option value="delta">Delta</option></select></label><label className="space-y-1 text-sm"><span>Delta</span><Input type="number" step="0.01" disabled={option.priceMode !== "delta"} value={option.priceDelta} onChange={(event) => updateOption(index, { priceDelta: event.target.value })} /></label></div><label className="flex items-center gap-2 text-sm"><Switch checked={option.emitsChildItem} onCheckedChange={(emitsChildItem) => updateOption(index, { emitsChildItem })} /> Genera item hijo</label>
      {option.priceMode === "delta" && <div className="space-y-2 rounded-md bg-muted/40 p-2"><p className="text-xs font-medium">Overrides de delta según el producto base</p>{option.priceOverrides.map((override, overrideIndex) => <div className="flex gap-2" key={override.id ?? overrideIndex}><select className="min-w-0 flex-1 rounded-md border bg-background p-1.5 text-xs" value={override.categoryId ?? ""} onChange={(event) => updateOption(index, { priceOverrides: option.priceOverrides.map((current, currentIndex) => currentIndex === overrideIndex ? { ...current, categoryId: event.target.value || null } : current) })}><option value="">Categoría…</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><Input className="w-20" type="number" step="0.01" value={override.priceDelta} onChange={(event) => updateOption(index, { priceOverrides: option.priceOverrides.map((current, currentIndex) => currentIndex === overrideIndex ? { ...current, priceDelta: event.target.value } : current) })} /><Button size="sm" variant="ghost" onClick={() => updateOption(index, { priceOverrides: option.priceOverrides.filter((_, currentIndex) => currentIndex !== overrideIndex) })}>×</Button></div>)}<Button size="sm" type="button" variant="outline" onClick={() => updateOption(index, { priceOverrides: [...option.priceOverrides, { categoryId: null, subcategoryId: null, productId: null, priceDelta: "0" }] })}>Agregar override</Button></div>}</div>)}</section>
      <section className="space-y-2 border-t pt-5"><Button variant="outline" className="w-full" onClick={onAddEdge}>Agregar arista desde este nodo</Button><p className="text-xs text-muted-foreground">La arista nueva se agrega al final de la prioridad y termina el flujo hasta que elijas otro destino.</p></section>
      <Button variant="destructive" className="w-full" disabled={!canDelete} onClick={onDelete}>Eliminar nodo</Button>{!canDelete && <p className="text-center text-xs text-muted-foreground">Un flujo debe conservar un nodo de entrada.</p>}</div>
  </aside>
}
